# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Download2Go' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Download2Go
pod 'RealmSwift'
pod 'BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod.git', tag: '2.24.0'

end
